### PR TITLE
Added project readme templates

### PR DESCRIPTION
**Pull request by priyank-mishra-1**
**Description**
Added two project readme templates.

**Requirements**
- [ ] Create a new Readme template for Projects

**Acceptance Criteria**
- [x] Create new Readme templates
- [x] Existing functionality is not broken

image

### CODE REVIEW

**Comment by priyank-mishra-1** [comment]
Please review my PR, this is for Issue #10

**Comment by TheShiveshNetwork** [comment]
Hey. @priyank-mishra-1 looks good, can you give some cool names to these templates. Also have you copied the first template from somewhere? I see a few lines at the top.

**Comment by priyank-mishra-1** [comment]
Yes, I took that one template from https://github.com/Louis3797/awesome-readme-template as it is public template. That's why I named it after him giving him credits.
Should I make entirely new templates? @TheShiveshNetwork

**Comment by priyank-mishra-1** [comment]
Hey @TheShiveshNetwork ,

I've updated the project templates with some cool names you suggested, such as Artemis and Nova. Additionally, I've removed the initial lines from the first template and replaced them with original content specific to our project.

Please take a look at the pull request and let me know if you have any feedback.

**Review by TheShiveshNetwork — APPROVED** [review]

**Comment by TheShiveshNetwork** [comment]
Looks good @priyank-mishra-1 can you make this PR from draft to ready so that I can merge it?

**Pull request merged**
