### PR TITLE
README.md Standardized

### PR DESCRIPTION
**Pull request by Code-Hacker26**
I have made necessary changes as infirmed earlier. Do check it out @TheShiveshNetwork

### CODE REVIEW

**Comment by Code-Hacker26** [comment]
@TheShiveshNetwork Could you please take a moment to review the updates I've made to the README.md file?

**Comment by TheShiveshNetwork** [comment]
Hey, @Code-Hacker26 nice work.
There are a few things.
1. As I told earlier, preview before sending pr. Check this
image
2. Take a screenshot of the home page of the website and paste it here.
image
3. Remove eslint from the built with section
4. I told last time to update every code block. See here:
image
It should be like this:
image
You'll be able to see the difference.
5. Remove the roadmap section. We don't need that
6. In the steps to Installation, also add "Get Gemini API". Add the documentation here: https://ai.google.dev/gemini-api/docs/api-key then instruct to create a .env.local and paste the api key there in:
```
NEXT_PUBLIC_GEMINI_API=
```

Please update these things. And make sure you are not leaving anything unfinished. Only then submit a pr for review. Also, make sure that you have resolved all the suggested changes from the last review. Since, I am seeing all of these changes were the ones I suggested earlier but have not been resolved in this review. Please keep this in my for every contribution to a project.

First complete this then I'd also like you to contribute more to the project, if there is anything like creating a new template or some ui updates. Submit an issue and I'll check whether it is good or not.

**Comment by TheShiveshNetwork** [comment]
> Hey, @Code-Hacker26 nice work. There are a few things.
> 
> 1. As I told earlier, preview before sending pr. Check this
>    image
> 2. Take a screenshot of the home page of the website and paste it here.
>    image
> 3. Remove eslint from the built with section
> 4. I told last time to update every code block. See here:
>    image
>    It should be like this:
>    image
>    You'll be able to see the difference.
> 5. Remove the roadmap section. We don't need that
> 
> Please update these things. And make sure you are not leaving anything unfinished. Only then submit a pr for review. Also, make sure that you have resolved all the suggested changes from the last review. Since, I am seeing all of these changes were the ones I suggested earlier but have not been resolved in this review. Please keep this in my for every contribution to a project.
> 
> First complete this then I'd also like you to contribute more to the project, if there is anything like creating a new template or some ui updates. Submit an issue and I'll check whether it is good or not.

Consider this code for the first:
```md
![Contributors][contributors-shield]
![Forks][forks-shield]
![Stargazers][stars-shield]
![Issues][issues-shield]
![GPL-2.0 License][license-shield]
```

**Comment by TheShiveshNetwork** [comment]
Hey @Code-Hacker26 if you are not able to complete it right now, I can take it from here. Please try to finish it soon.

**Comment by Code-Hacker26** [comment]
@TheShiveshNetwork apologies for the delay , I was busy in cllg projects .But i will see to it by tonight

**Comment by Code-Hacker26** [comment]
@TheShiveshNetwork i have made necessary changes ,just wanted to ask regarding the product images of ABOUT section.

Shall i paste the Screenshot  images in the assets folder ?

**Comment by Code-Hacker26** [comment]
@TheShiveshNetwork,
I wanted to inform you that I have generated a Pull Request with all the changes requested for the README.md file. The updates include a standardized format, improved content clarity, and corrected errors.

Please review the Pull Request at your convenience and let me know if any further changes are required.
Kindly take note that I have added 2 images in assets folder in public DIR.

Best regards,
@Code-Hacker26

**Pull request closed without merging**
